import { Platform, StyleSheet } from "react-native";
import { fonts, layout, lineHeight, radius, semanticRadius, spacing, typography } from "../../theme/tokens";
import { FONT_DISPLAY, FONT_DISPLAY_SEMI, ALCHEMY, HERITAGE } from "../../theme/customerAlchemy";
import { WEB_HEADER_HEIGHT, WEB_Z_INDEX } from "../../theme/web";
import { CUSTOMER_BOTTOM_NAV_BAR_HEIGHT } from "../../theme/screenLayout";
import { spacing as homeSpacing } from "../../styles/spacing";
import { BRAND_HOME_TOP_BAR_LAYOUT_HEIGHT } from "../../constants/brand";

const HOME_HEADER_INK = "#0E0E0E";
const HOME_LINE = "#E8E6E1";

function createHomeStyles(c, shadowLift, shadowPremium, isDark, windowWidth = 0, insets = { top: 0, bottom: 0 }) {
  const sectionGap = windowWidth >= 600 ? 40 : 32;
  const cardPadding = windowWidth >= 600 ? homeSpacing.lg : homeSpacing.base;
  const productGridGap = windowWidth >= 600 ? 14 : 10;
  const safeTopInset = Number(insets?.top || 0);
  const safeBottomInset = Number(insets?.bottom || 0);
  const homeHeaderBg = isDark ? c.surface : ALCHEMY.cream;
  const homeLine = c.border;
  return StyleSheet.create({
    screen: {
      flex: 1,
      width: "100%",
      alignSelf: "stretch",
      maxWidth: "100%",
      backgroundColor: c.background,
      ...Platform.select({
        web: { minHeight: "100%", height: "100%" },
        default: {},
      }),
    },
    gradientFill: {
      flex: 1,
      width: "100%",
    },
    scrollMain: {
      flex: 1,
      width: "100%",
      ...Platform.select({
        web: {
          minHeight: 0,
          overflowY: "auto",
          WebkitOverflowScrolling: "touch",
          touchAction: "pan-y",
        },
        default: {},
      }),
    },
    headerWrap: {
      paddingBottom: Platform.select({ web: homeSpacing.base, default: homeSpacing.sm }),
      ...Platform.select({
        web: { width: "100%", alignSelf: "stretch", minWidth: 0 },
        default: {},
      }),
    },
    headerAmbientCard: {
      position: "relative",
      borderRadius: radius.xxl,
      overflow: Platform.OS === "web" ? "visible" : "hidden",
      borderWidth: 0,
      marginBottom: spacing.md,
      ...Platform.select({
        ios: {
          shadowColor: "#18181B",
          shadowOffset: { width: 0, height: 10 },
          shadowOpacity: isDark ? 0.22 : 0.09,
          shadowRadius: 20,
        },
        android: { elevation: isDark ? 5 : 4 },
        web: {
          boxShadow: isDark
            ? "0 16px 44px rgba(0,0,0,0.32), inset 0 1px 0 rgba(255,255,255,0.05)"
            : "0 18px 48px rgba(9, 9, 11, 0.09), 0 5px 16px rgba(24, 24, 27, 0.04), inset 0 1px 0 rgba(255, 253, 251, 0.95), inset 0 0 0 1px rgba(255,255,255,0.45)",
        },
        default: {
          borderRadius: 0,
          borderWidth: 0,
          borderTopWidth: 0,
          marginBottom: spacing.sm,
        },
      }),
    },
    headerAmbientCardLight: {
      borderColor: homeLine,
      backgroundColor: homeHeaderBg,
      ...Platform.select({
        web: {
          backdropFilter: "none",
        },
        default: {
          backgroundColor: homeHeaderBg,
        },
      }),
    },
    headerAmbientCardScrolled: {
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: homeLine,
    },
    headerAmbientCardDark: {
      borderColor: homeLine,
      backgroundColor: homeHeaderBg,
    },
    topBarShellNested: {
      paddingTop: 4,
      paddingBottom: 4,
      paddingHorizontal: spacing.xs,
    },
    headerInnerDivider: {
      height: StyleSheet.hairlineWidth,
      marginHorizontal: spacing.lg,
      marginTop: spacing.xs,
      marginBottom: spacing.sm,
      backgroundColor: homeLine,
    },
    headerInnerDividerDark: {
      backgroundColor: c.border,
    },
    cartBtnInner: {
      width: 44,
      minHeight: 40,
      alignItems: "center",
      justifyContent: "center",
      position: "relative",
    },
    cartBadge: {
      position: "absolute",
      top: 2,
      right: 0,
      minWidth: 18,
      height: 18,
      paddingHorizontal: 4,
      borderRadius: 9,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 2,
    },
    cartBadgeText: {
      color: c.onPrimary,
      fontSize: 10,
      fontFamily: fonts.semibold,
      lineHeight: 12,
    },
    alchemyTopBar: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: homeSpacing.md,
      minHeight: BRAND_HOME_TOP_BAR_LAYOUT_HEIGHT,
      marginBottom: homeSpacing.xs,
    },
    wordmarkBlock: {
      flex: 1,
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      alignSelf: "stretch",
      paddingHorizontal: spacing.xs,
      minWidth: 0,
    },
    topBarTagline: {
      marginTop: -2,
      fontSize: Platform.OS === "web" ? typography.overline : 12,
      fontFamily: fonts.regular,
      letterSpacing: 0.6,
      textAlign: "center",
      lineHeight: Platform.OS === "web" ? lineHeight.overline : 16,
      color: c.textMuted,
    },
    topBarLogo: {
      flexShrink: 1,
      maxWidth: "100%",
      alignSelf: "center",
      textAlign: "center",
      ...Platform.select({
        ios: {
          shadowColor: "#18181B",
          shadowOffset: { width: 0, height: 1 },
          shadowOpacity: 0.08,
          shadowRadius: 2,
        },
        web: {
          boxShadow: "0 1px 4px rgba(24, 24, 27, 0.06)",
        },
        default: {},
      }),
    },
    alchemyIconBtn: {
      width: 44,
      minHeight: 42,
      alignItems: "center",
      justifyContent: "center",
      alignSelf: "center",
      borderRadius: radius.md,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: "rgba(100, 116, 139, 0.16)",
      backgroundColor: "rgba(255, 255, 255, 0.88)",
      ...Platform.select({
        web: { cursor: "pointer" },
        default: {},
      }),
    },
    searchWrap: {
      marginTop: 16,
      marginBottom: homeSpacing.md,
      paddingHorizontal: spacing.sm,
      ...Platform.select({
        web: { width: "100%", alignSelf: "stretch", minWidth: 0 },
        default: {},
      }),
    },
    webSearchRail: {
      flexDirection: "column",
      alignItems: "stretch",
      gap: spacing.sm,
      width: "100%",
      maxWidth: 520,
      marginBottom: homeSpacing.lg,
      padding: spacing.sm,
      borderRadius: 14,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: isDark ? "rgba(255,255,255,0.12)" : "rgba(63,63,70,0.2)",
      backgroundColor: c.surface,
      ...Platform.select({
        web: { boxShadow: "0 2px 8px rgba(0,0,0,0.04)" },
        default: {},
      }),
    },
    webSearchRailWithLocation: {
      alignItems: "stretch",
    },
    conciergeBar: {
      flexDirection: "row",
      alignItems: "center",
      flexWrap: "nowrap",
      gap: homeSpacing.md,
      borderRadius: 14,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: isDark ? "rgba(255,255,255,0.12)" : "rgba(63,63,70,0.2)",
      backgroundColor: c.surface,
      padding: homeSpacing.md,
      ...Platform.select({
        web: { boxShadow: "0 2px 8px rgba(0,0,0,0.04)" },
        ios: {
          shadowColor: "#000000",
          shadowOffset: { width: 0, height: 2 },
          shadowOpacity: 0.04,
          shadowRadius: 8,
        },
        android: { elevation: 1 },
      }),
    },
    conciergeBarDark: {
      borderColor: "rgba(255,255,255,0.14)",
    },
    conciergeBarStacked: {
      alignItems: "stretch",
      gap: spacing.xs,
    },
    conciergeTopRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: homeSpacing.md,
    },
    conciergeLocationChip: {
      minHeight: 44,
      maxWidth: Platform.OS === "web" ? "100%" : "60%",
      flexDirection: "row",
      alignItems: "center",
      gap: homeSpacing.xs,
      borderRadius: radius.pill,
      paddingHorizontal: spacing.sm,
      backgroundColor: isDark ? "rgba(255,255,255,0.08)" : "rgba(248,250,252,0.92)",
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: isDark ? "rgba(255,255,255,0.16)" : "rgba(100,116,139,0.2)",
    },
    conciergeLocationChipWeb: {
      maxWidth: "100%",
      justifyContent: "flex-start",
    },
    conciergeLocationChipStacked: {
      maxWidth: "100%",
      flex: 1,
    },
    conciergeLocationText: {
      flex: 1,
      fontFamily: fonts.semibold,
      fontSize: typography.bodySmall,
      color: c.textPrimary,
    },
    conciergeSearchWrap: {
      position: "relative",
      flex: 1,
      minWidth: 0,
    },
    conciergeSearchWrapFocused: {
      ...Platform.select({
        web: { width: "100%" },
        default: {},
      }),
    },
    conciergeSearchWrapStacked: {
      width: "100%",
      flexBasis: "100%",
      flexGrow: 0,
    },
    conciergeSearchInputShell: {
      minHeight: 44,
      borderRadius: radius.pill,
      borderColor: isDark ? "rgba(255,255,255,0.16)" : "rgba(100,116,139,0.2)",
      backgroundColor: isDark ? "rgba(255,255,255,0.08)" : "rgba(255,255,255,0.98)",
      ...Platform.select({
        web: { transition: "all 220ms ease" },
        default: {},
      }),
    },
    conciergeSearchInput: {
      minHeight: 24,
      paddingVertical: Platform.OS === "web" ? 6 : 4,
      fontSize: typography.bodySmall + 1,
    },
    conciergeIconBtn: {
      width: 44,
      minHeight: 44,
      borderRadius: radius.pill,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: isDark ? "rgba(255,255,255,0.16)" : "rgba(100,116,139,0.2)",
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: isDark ? "rgba(255,255,255,0.08)" : "rgba(248,250,252,0.92)",
    },
    conciergeIconBtnWeb: {
      alignSelf: "flex-start",
    },
    conciergeUnreadDot: {
      position: "absolute",
      top: 10,
      right: 10,
      width: 6,
      height: 6,
      borderRadius: 999,
      backgroundColor: c.rating,
      borderWidth: 1,
      borderColor: c.surface,
    },
    conciergePressed: {
      opacity: 0.78,
    },
    recentSearchDropdown: {
      position: "absolute",
      top: 48,
      left: 0,
      right: 0,
      zIndex: 10,
      borderRadius: radius.lg,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: isDark ? "rgba(255,255,255,0.14)" : "rgba(100,116,139,0.2)",
      backgroundColor: c.surface,
      paddingVertical: spacing.xs,
      ...Platform.select({
        web: { boxShadow: "0 8px 24px rgba(15,23,42,0.08)" },
        ios: {
          shadowColor: "#0F172A",
          shadowOffset: { width: 0, height: 8 },
          shadowOpacity: 0.08,
          shadowRadius: 16,
        },
        android: { elevation: 3 },
      }),
    },
    recentSearchTitle: {
      paddingHorizontal: spacing.sm,
      paddingBottom: homeSpacing.xs,
      fontSize: typography.caption,
      fontFamily: fonts.semibold,
      color: c.textMuted,
    },
    recentSearchItem: {
      minHeight: 44,
      paddingHorizontal: spacing.sm,
      flexDirection: "row",
      alignItems: "center",
      gap: spacing.xs,
    },
    recentSearchItemText: {
      flex: 1,
      fontSize: typography.bodySmall,
      color: c.textPrimary,
      fontFamily: fonts.medium,
    },
    recentSearchEmpty: {
      minHeight: 44,
      paddingHorizontal: spacing.sm,
      textAlignVertical: "center",
      fontSize: typography.bodySmall,
      color: c.textMuted,
      fontFamily: fonts.regular,
    },
    searchGradientFrame: {
      borderRadius: 999,
      padding: 4,
      ...Platform.select({
        ios: {
          shadowColor: ALCHEMY.brown,
          shadowOffset: { width: 0, height: 6 },
          shadowOpacity: isDark ? 0.2 : 0.14,
          shadowRadius: 16,
        },
        android: { elevation: isDark ? 5 : 4 },
        web: {
          boxShadow: isDark
            ? "0 12px 40px rgba(0,0,0,0.35)"
            : "0 8px 24px rgba(15, 23, 42, 0.08), 0 2px 8px rgba(15, 23, 42, 0.05)",
        },
        default: {
          padding: 0,
        },
      }),
    },
    searchInner: {
      borderRadius: 999,
      overflow: "hidden",
    },
    heroImageOuter: {
      marginBottom: 32,
      borderRadius: radius.xxl + 2,
      overflow: "hidden",
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: isDark ? "rgba(255,255,255,0.1)" : "rgba(100, 116, 139, 0.14)",
      ...Platform.select({
        web: {
          width: "100%",
          maxWidth: layout.maxContentWidth,
          alignSelf: "center",
          boxShadow: isDark
            ? "0 24px 64px rgba(0,0,0,0.45), 0 8px 24px rgba(0,0,0,0.25)"
            : "0 20px 42px rgba(15, 23, 42, 0.11), 0 6px 14px rgba(15, 23, 42, 0.06)",
        },
        ios: {
          shadowColor: "#09090B",
          shadowOffset: { width: 0, height: 14 },
          shadowOpacity: isDark ? 0.4 : 0.2,
          shadowRadius: 24,
        },
        android: { elevation: isDark ? 8 : 5 },
        default: {},
      }),
    },
    heroSlider: {
      width: "100%",
    },
    heroPremiumFill: {
      position: "relative",
      width: "100%",
      justifyContent: "flex-end",
      backgroundColor: isDark ? "#0B1120" : "#111827",
      overflow: "hidden",
      padding: Platform.select({ web: spacing.md, default: spacing.sm }),
    },
    heroSlideFrame: {
      flex: 1,
      borderRadius: radius.xxl,
      overflow: "hidden",
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: "rgba(255, 252, 248, 0.12)",
      backgroundColor: "#120D0A",
    },
    heroSlideMedia: {
      ...StyleSheet.absoluteFillObject,
    },
    heroDotsPill: {
      position: "absolute",
      bottom: 16,
      left: 0,
      right: 0,
      alignItems: "center",
      zIndex: 4,
    },
    heroDotBackdrop: {
      paddingHorizontal: 4,
      paddingVertical: 4,
      borderRadius: radius.pill,
      backgroundColor: "transparent",
      borderWidth: 0,
      borderColor: "transparent",
      ...Platform.select({
        web: {
          backdropFilter: "none",
          WebkitBackdropFilter: "none",
        },
        default: {},
      }),
    },
    heroDotRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
    },
    heroDotHit: {
      minHeight: 12,
      paddingVertical: 4,
      paddingHorizontal: 4,
      ...Platform.select({
        web: { cursor: "pointer" },
        default: {},
      }),
    },
    heroDot: {
      height: 4,
      borderRadius: 9999,
    },
    heroDotIdle: {
      backgroundColor: "rgba(255,255,255,0.32)",
    },
    heroDotActive: {
      backgroundColor: "rgba(255,255,255,0.95)",
    },
    heroBrandLogo: {
      alignSelf: "flex-start",
      maxWidth: "100%",
      marginBottom: spacing.sm,
    },
    heroBrandLogoOnPhoto: {
      opacity: 0.98,
    },
    heroImageInner: {
      position: "relative",
      zIndex: 2,
      paddingTop: Platform.select({ web: homeSpacing["2xl"], default: homeSpacing.xl }),
      paddingHorizontal: Platform.select({ web: 30, default: 26 }),
      paddingBottom: Platform.select({ web: 66, default: 60 }),
    },
    heroOverline: {
      color: "rgba(255,255,255,0.65)",
      fontSize: 11,
      fontFamily: fonts.semibold,
      letterSpacing: 1.8,
      textTransform: "uppercase",
      marginBottom: spacing.xs,
    },
    heroSlideCounter: {
      position: "absolute",
      top: 16,
      right: 16,
      zIndex: 4,
      paddingHorizontal: spacing.sm,
      paddingVertical: homeSpacing.xs,
      borderRadius: radius.pill,
      backgroundColor: "rgba(8, 6, 4, 0.52)",
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: "rgba(255, 252, 248, 0.22)",
      ...Platform.select({
        web: {
          backdropFilter: "blur(12px)",
          WebkitBackdropFilter: "blur(12px)",
        },
        default: {},
      }),
    },
    heroSlideCounterText: {
      color: c.heroForeground,
      fontSize: typography.caption,
      fontFamily: fonts.semibold,
      letterSpacing: 1.2,
      fontVariant: ["tabular-nums"],
    },
    heroSlideCounterSep: {
      color: "rgba(255, 252, 248, 0.55)",
      fontFamily: fonts.semibold,
      letterSpacing: 0,
    },
    heroEditorialRow: {
      flexDirection: "row",
      alignItems: "center",
      flexWrap: "wrap",
      gap: spacing.sm,
      marginBottom: homeSpacing.md,
      maxWidth: 560,
    },
    heroKickerText: {
      color: "rgba(255, 252, 248, 0.92)",
      fontSize: typography.overline + 1,
      fontFamily: fonts.semibold,
      letterSpacing: 2,
      textTransform: "uppercase",
      ...Platform.select({
        web: { textShadow: "0 1px 12px rgba(8, 6, 4, 0.55)" },
        default: {
          textShadowColor: "rgba(8, 6, 4, 0.55)",
          textShadowOffset: { width: 0, height: 1 },
          textShadowRadius: 10,
        },
      }),
    },
    heroNavRail: {
      position: "absolute",
      top: "50%",
      left: 12,
      right: 12,
      marginTop: -20,
      zIndex: 4,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    heroNavButton: {
      width: 40,
      height: 40,
      borderRadius: semanticRadius.full,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "rgba(255,255,255,0.10)",
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.16)",
      ...Platform.select({
        web: {
          cursor: "pointer",
          backdropFilter: "blur(12px)",
          WebkitBackdropFilter: "blur(12px)",
        },
        default: {},
      }),
    },
    heroNavButtonHover: {
      backgroundColor: "rgba(255,255,255,0.18)",
    },
    heroNavButtonPressed: {
      opacity: 1,
      backgroundColor: "rgba(255,255,255,0.18)",
      transform: [{ scale: 0.98 }],
    },
    heroBadgePill: {
      paddingHorizontal: homeSpacing.md,
      paddingVertical: homeSpacing.xs,
      borderRadius: radius.pill,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: isDark ? "rgba(255,255,255,0.24)" : "rgba(255,255,255,0.28)",
      backgroundColor: "rgba(8, 6, 4, 0.34)",
    },
    heroBadgePillText: {
      color: "#FEF2F2",
      fontSize: typography.overline,
      fontFamily: fonts.semibold,
      letterSpacing: 1.2,
    },
    heroDisplayTitle: {
      fontFamily: FONT_DISPLAY,
      fontSize: Platform.OS === "web" ? 36 : 32,
      lineHeight: Platform.OS === "web" ? 42 : 37,
      letterSpacing: Platform.OS === "web" ? -0.55 : -0.4,
      marginBottom: 0,
      maxWidth: 640,
      ...Platform.select({
        web: {
          textShadow: isDark
            ? "0 2px 28px rgba(8, 6, 4, 0.45)"
            : "0 2px 14px rgba(255, 255, 255, 0.6)",
        },
        default: {
          textShadowColor: isDark ? "rgba(8, 6, 4, 0.45)" : "rgba(255, 255, 255, 0.6)",
          textShadowOffset: { width: 0, height: 2 },
          textShadowRadius: isDark ? 18 : 10,
        },
      }),
    },
    heroDisplayOnPhoto: {
      color: c.heroForeground,
      ...Platform.select({
        web: { textShadow: "0 2px 22px rgba(8, 6, 4, 0.65)" },
        default: {
          textShadowColor: "rgba(8, 6, 4, 0.65)",
          textShadowOffset: { width: 0, height: 2 },
          textShadowRadius: 16,
        },
      }),
    },
    heroDisplaySub: {
      marginTop: spacing.xs,
      fontSize: Platform.OS === "web" ? typography.body + 1 : typography.body,
      fontFamily: fonts.medium,
      lineHeight: Platform.OS === "web" ? 25 : 24,
      maxWidth: 560,
      opacity: 0.96,
      ...Platform.select({
        web: { textShadow: "0 1px 10px rgba(8, 6, 4, 0.35)" },
        default: {
          textShadowColor: "rgba(8, 6, 4, 0.35)",
          textShadowOffset: { width: 0, height: 1 },
          textShadowRadius: 10,
        },
      }),
    },
    heroDisplaySubOnPhoto: {
      color: "rgba(255, 252, 248, 0.86)",
      ...Platform.select({
        web: { textShadow: "0 1px 12px rgba(8, 6, 4, 0.55)" },
        default: {
          textShadowColor: "rgba(8, 6, 4, 0.55)",
          textShadowOffset: { width: 0, height: 1 },
          textShadowRadius: 12,
        },
      }),
    },
    heroEditorialNote: {
      marginTop: spacing.sm,
      maxWidth: 520,
      color: "rgba(255, 252, 248, 0.84)",
      fontSize: typography.caption,
      fontFamily: fonts.medium,
      lineHeight: lineHeight.caption + 4,
      ...Platform.select({
        web: { textShadow: "0 1px 10px rgba(8, 6, 4, 0.45)" },
        default: {
          textShadowColor: "rgba(8, 6, 4, 0.45)",
          textShadowOffset: { width: 0, height: 1 },
          textShadowRadius: 10,
        },
      }),
    },
    heroPromiseRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: spacing.sm,
      marginTop: spacing.md,
      maxWidth: 620,
    },
    heroPromiseChip: {
      flexDirection: "row",
      alignItems: "center",
      gap: homeSpacing.sm,
      paddingHorizontal: homeSpacing.md,
      paddingVertical: 8,
      borderRadius: radius.pill,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: "rgba(255, 252, 248, 0.22)",
      backgroundColor: "rgba(8, 6, 4, 0.34)",
      ...Platform.select({
        web: {
          backdropFilter: "blur(10px)",
          WebkitBackdropFilter: "blur(10px)",
        },
        default: {},
      }),
    },
    heroPromiseChipText: {
      color: c.heroForeground,
      fontSize: typography.caption,
      fontFamily: fonts.semibold,
      letterSpacing: 0.2,
    },
    heroCtaButton: {
      marginTop: spacing.lg,
    },
    heroEditorialCta: {
      alignSelf: "flex-start",
      marginTop: 12,
      minHeight: 46,
      borderRadius: 999,
      paddingHorizontal: homeSpacing.xl,
      paddingVertical: spacing.sm,
      backgroundColor: "rgba(255,255,255,0.98)",
      borderWidth: 0,
      borderColor: "transparent",
      ...Platform.select({
        web: {
          cursor: "pointer",
          transition: "transform 0.18s ease, opacity 0.18s ease, box-shadow 0.18s ease",
          boxShadow: "inset 0 1px 0 rgba(255,255,255,0.2), 0 10px 24px rgba(8, 6, 4, 0.34)",
        },
        default: {},
      }),
    },
    heroEditorialCtaPressed: {
      opacity: 0.92,
      transform: [{ scale: 0.99 }],
    },
    heroEditorialCtaText: {
      color: "#0E1729",
      fontSize: 14,
      fontFamily: fonts.semibold,
      letterSpacing: 1.1,
      textTransform: "uppercase",
    },
    promoVideoWrap: {
      width: "100%",
      maxWidth: layout.maxContentWidth,
      alignSelf: "center",
      marginBottom: homeSpacing["3xl"],
      borderRadius: radius.xxl,
      overflow: "hidden",
      borderWidth: 1,
      borderColor: isDark ? "rgba(255,255,255,0.12)" : "rgba(100, 116, 139, 0.14)",
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: isDark ? "rgba(255,255,255,0.12)" : "#E8E6E1",
      backgroundColor: "#110B07",
      padding: Platform.OS === "web" ? 10 : 8,
      ...Platform.select({
        web: {
          boxShadow: isDark
            ? "0 28px 72px rgba(0,0,0,0.56), 0 8px 26px rgba(0,0,0,0.3), inset 0 1px 0 rgba(255,255,255,0.08)"
            : "0 20px 48px rgba(15, 23, 42, 0.14), 0 7px 18px rgba(15, 23, 42, 0.08), inset 0 1px 0 rgba(255,255,255,0.76)",
        },
        ios: {
          shadowColor: "#09090B",
          shadowOffset: { width: 0, height: 10 },
          shadowOpacity: isDark ? 0.36 : 0.18,
          shadowRadius: 18,
        },
        android: { elevation: isDark ? 6 : 4 },
        default: {},
      }),
    },
    promoVideoFrame: {
      borderRadius: radius.xl + 2,
      overflow: "hidden",
      backgroundColor: "#0A0705",
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: isDark ? "rgba(255, 252, 248, 0.14)" : "rgba(255, 252, 248, 0.24)",
      ...Platform.select({
        web: {
          boxShadow: isDark
            ? "inset 0 0 0 1px rgba(255, 252, 248, 0.08)"
            : "inset 0 0 0 1px rgba(255, 252, 248, 0.4)",
        },
        default: {},
      }),
    },
    promoVideo: {
      width: "100%",
      height: Platform.OS === "web" ? 400 : 260,
      backgroundColor: "#120D08",
    },
    promoSheen: {
      ...StyleSheet.absoluteFillObject,
    },
    promoMuteBtn: {
      position: "absolute",
      right: spacing.md,
      bottom: spacing.md,
      zIndex: 3,
      minHeight: 44,
      paddingHorizontal: homeSpacing.md,
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "row",
      gap: homeSpacing.sm,
      borderRadius: 22,
      borderWidth: 1,
      borderColor: "rgba(255, 252, 248, 0.48)",
      backgroundColor: "rgba(12, 9, 7, 0.66)",
      ...Platform.select({
        web: {
          cursor: "pointer",
          boxShadow: "0 8px 20px rgba(8, 6, 4, 0.5), inset 0 1px 0 rgba(255, 252, 248, 0.28)",
          backdropFilter: "blur(10px)",
          WebkitBackdropFilter: "blur(10px)",
        },
        default: {},
      }),
    },
    promoMuteText: {
      color: c.heroForeground,
      fontSize: typography.overline + 1,
      fontFamily: fonts.semibold,
      letterSpacing: 0.35,
      textTransform: "uppercase",
    },
    promoMuteBtnAttention: {
      borderColor: "rgba(255, 252, 248, 0.76)",
      backgroundColor: "rgba(12, 9, 7, 0.78)",
      ...Platform.select({
        web: {
          boxShadow: "0 10px 24px rgba(8, 6, 4, 0.56), inset 0 1px 0 rgba(255, 252, 248, 0.4)",
        },
        default: {},
      }),
    },
    jumpNavSticky: {
      alignSelf: "center",
      marginBottom: spacing.md,
      ...Platform.select({
        web: {
          position: "sticky",
          top: WEB_HEADER_HEIGHT + 8,
          zIndex: 11,
        },
        default: {},
      }),
    },
    jumpNavInner: {
      flexDirection: "row",
      alignItems: "center",
      gap: homeSpacing.sm,
      paddingVertical: homeSpacing.sm,
      paddingHorizontal: 8,
      borderRadius: 9999,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: isDark ? "rgba(255,255,255,0.22)" : "rgba(63, 63, 70, 0.16)",
      backgroundColor: isDark ? "rgba(15, 12, 10, 0.72)" : "rgba(255, 252, 247, 0.86)",
      ...Platform.select({
        web: {
          backdropFilter: "saturate(160%) blur(14px)",
          WebkitBackdropFilter: "saturate(160%) blur(14px)",
          boxShadow: isDark
            ? "0 12px 28px rgba(0,0,0,0.42), inset 0 1px 0 rgba(255,255,255,0.04)"
            : "0 10px 24px rgba(63, 63, 70, 0.12), inset 0 1px 0 rgba(255,255,255,0.7)",
        },
        default: {},
      }),
    },
    jumpNavChip: {
      flexDirection: "row",
      alignItems: "center",
      gap: homeSpacing.sm,
      paddingHorizontal: spacing.md,
      paddingVertical: homeSpacing.sm,
      borderRadius: 9999,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: "transparent",
      backgroundColor: "transparent",
      ...Platform.select({
        web: {
          cursor: "pointer",
          transitionProperty: "transform, background-color, color, border-color",
          transitionDuration: "180ms",
        },
        default: {},
      }),
    },
    jumpNavChipActive: {
      backgroundColor: isDark ? "rgba(148,163,184,0.16)" : c.secondarySoft,
      borderColor: isDark ? "rgba(148,163,184,0.42)" : c.secondaryBorder,
      ...Platform.select({
        web: {
          boxShadow: isDark
            ? "0 6px 14px rgba(148,163,184,0.16)"
            : "0 6px 14px rgba(63, 63, 70, 0.14)",
        },
        default: {},
      }),
    },
    jumpNavDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: c.accentGreen || c.secondary,
    },
    jumpNavChipTextActive: {
      color: c.accentGreen || c.secondaryDark,
    },
    jumpNavChipText: {
      fontSize: typography.caption,
      fontFamily: fonts.bold,
      color: isDark ? c.textPrimary : ALCHEMY.brown,
      letterSpacing: 0.4,
    },
    trustSectionWrap: {
      width: "100%",
      marginTop: 0,
      marginBottom: sectionGap,
      alignItems: "stretch",
      ...Platform.select({
        web: {
          maxWidth: layout.maxContentWidth,
          alignSelf: "center",
        },
        default: {},
      }),
    },
    liveOrderWrap: {
      width: "100%",
      marginBottom: spacing.lg,
      ...Platform.select({
        web: {
          maxWidth: layout.maxContentWidth,
          alignSelf: "center",
        },
        default: {},
      }),
    },
    liveOrderCard: {
      borderRadius: radius.xxl,
      paddingVertical: homeSpacing.lg,
      paddingHorizontal: spacing.lg,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: isDark ? "rgba(255,255,255,0.2)" : "rgba(63, 63, 70, 0.14)",
    },
    liveOrderOverline: {
      fontSize: typography.overline + 1,
      fontFamily: fonts.semibold,
      letterSpacing: 1.4,
      textTransform: "uppercase",
      color: isDark ? ALCHEMY.goldBright : ALCHEMY.brown,
      marginBottom: homeSpacing.xs,
    },
    liveOrderTitle: {
      fontSize: typography.body,
      fontFamily: fonts.bold,
      color: c.textPrimary,
      marginBottom: spacing.sm,
    },
    liveOrderMetaRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: spacing.sm,
      marginBottom: spacing.sm,
    },
    liveOrderStatusPill: {
      paddingHorizontal: spacing.sm,
      paddingVertical: homeSpacing.sm,
      borderRadius: radius.pill,
      borderWidth: StyleSheet.hairlineWidth,
      backgroundColor: c.secondarySoft,
    },
    liveOrderStatusText: {
      fontSize: typography.caption,
      fontFamily: fonts.bold,
    },
    liveOrderAmount: {
      fontSize: typography.body,
      fontFamily: fonts.semibold,
      color: c.textPrimary,
    },
    liveOrderActions: {
      flexDirection: "row",
      alignItems: "center",
      gap: spacing.sm,
    },
    liveOrderBtn: {
      flex: 1,
      borderRadius: radius.lg,
      paddingVertical: spacing.sm,
      alignItems: "center",
      justifyContent: "center",
    },
    liveOrderBtnPrimary: {
      backgroundColor: c.primary,
    },
    liveOrderBtnPrimaryText: {
      color: c.onPrimary,
      fontSize: typography.bodySmall,
      fontFamily: fonts.bold,
    },
    liveOrderBtnGhost: {
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: isDark ? c.border : "rgba(63, 63, 70, 0.2)",
      backgroundColor: isDark ? "rgba(255,255,255,0.04)" : "rgba(255,255,255,0.64)",
    },
    liveOrderBtnGhostText: {
      fontSize: typography.bodySmall,
      fontFamily: fonts.semibold,
    },
    trustSectionEyebrow: {
      fontSize: typography.overline + 1,
      fontFamily: fonts.semibold,
      letterSpacing: 2,
      textTransform: "uppercase",
      textAlign: "center",
      marginBottom: homeSpacing.base,
      width: "100%",
    },
    homeSectionOverline: {
      fontSize: typography.overline + 1,
      fontFamily: fonts.semibold,
      letterSpacing: 1.65,
      textTransform: "uppercase",
      textAlign: "center",
      marginBottom: spacing.sm,
      width: "100%",
    },
    homeShopOverline: {
      marginBottom: homeSpacing.md,
    },
    shopDiscoveryHint: {
      fontSize: typography.caption,
      fontFamily: fonts.regular,
      lineHeight: lineHeight.caption + 4,
      textAlign: "center",
      marginBottom: spacing.sm,
      paddingHorizontal: spacing.md,
      opacity: 0.92,
    },
    shopDiscoveryIntro: {
      fontSize: typography.body,
      fontFamily: FONT_DISPLAY_SEMI,
      lineHeight: lineHeight.body + 4,
      textAlign: "center",
      marginBottom: homeSpacing.lg,
      paddingHorizontal: spacing.sm,
      letterSpacing: -0.2,
    },
    shopDiscoverySection: {
      width: "100%",
      ...Platform.select({
        web: {
          maxWidth: layout.maxContentWidth,
          alignSelf: "center",
        },
        default: {},
      }),
      marginBottom: homeSpacing["3xl"],
    },
    trustStripAmbient: {
      ...StyleSheet.absoluteFillObject,
      borderRadius: 14,
      opacity: Platform.OS === "web" ? 0.7 : 1,
    },
    homeErrorBanner: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: spacing.sm,
      paddingVertical: homeSpacing.base,
      paddingHorizontal: homeSpacing.lg,
      marginBottom: homeSpacing.lg,
      borderRadius: radius.lg + 2,
      borderWidth: StyleSheet.hairlineWidth,
      maxWidth: layout.maxContentWidth,
      width: "100%",
      alignSelf: "center",
    },
    outOfAreaBanner: {
      width: "100%",
      maxWidth: layout.maxContentWidth,
      alignSelf: "center",
      flexDirection: "row",
      alignItems: "center",
      gap: homeSpacing.sm,
      borderWidth: 1,
      borderRadius: 12,
      paddingVertical: homeSpacing.md,
      paddingHorizontal: homeSpacing.base,
      marginBottom: homeSpacing.base,
    },
    outOfAreaIcon: {
      flexShrink: 0,
    },
    outOfAreaText: {
      flex: 1,
      fontFamily: fonts.regular,
      fontSize: 14,
      lineHeight: Math.round(14 * 1.45),
    },
    outOfAreaLinkBtn: {
      paddingVertical: homeSpacing.xs,
      paddingHorizontal: homeSpacing.sm,
      borderRadius: radius.pill,
    },
    outOfAreaLinkBtnPressed: {
      opacity: 0.8,
    },
    outOfAreaLinkText: {
      fontSize: 13,
      fontFamily: fonts.semibold,
      lineHeight: Math.round(13 * 1.4),
    },
    homeErrorIcon: {
      marginTop: homeSpacing.xs,
      flexShrink: 0,
    },
    trustStrip: {
      position: "relative",
      overflow: "hidden",
      borderRadius: 14,
      ...Platform.select({
        web: {
          width: "100%",
          maxWidth: layout.maxContentWidth,
          alignSelf: "center",
        },
        default: {},
      }),
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
      backgroundColor: c.surface,
    },
    trustStripDark: {
      borderColor: c.border,
    },
    trustStripInner: {
      flexDirection: "row",
      alignItems: "stretch",
      justifyContent: "space-between",
      width: "100%",
      zIndex: 1,
    },
    trustStripInnerStacked: {
      flexDirection: "column",
    },
    trustDivider: {
      width: StyleSheet.hairlineWidth,
      alignSelf: "stretch",
      marginVertical: 0,
      flexShrink: 0,
      opacity: 1,
    },
    trustDividerStacked: {
      width: "100%",
      height: StyleSheet.hairlineWidth,
    },
    trustDividerLight: {
      backgroundColor: c.border,
    },
    trustDividerDark: {
      backgroundColor: c.border,
    },
    trustCell: {
      flex: 1,
      minWidth: 0,
      alignItems: "flex-start",
      justifyContent: "flex-start",
      paddingHorizontal: 16,
      paddingVertical: 16,
      ...Platform.select({
        web: { cursor: "pointer" },
        default: {},
      }),
    },
    trustCellStacked: {
      width: "100%",
    },
    trustCellPressed: {
      opacity: 0.86,
    },
    trustIconBadge: {
      width: 22,
      height: 22,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 8,
    },
    trustIconBadgeLight: {
      backgroundColor: ALCHEMY.goldSoft,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: "rgba(63, 63, 70, 0.1)",
      ...Platform.select({
        ios: {
          shadowColor: ALCHEMY.brown,
          shadowOffset: { width: 0, height: 2 },
          shadowOpacity: 0.06,
          shadowRadius: 4,
        },
        default: {},
      }),
    },
    trustIconBadgeDark: {
      backgroundColor: "rgba(134, 239, 172, 0.12)",
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: "rgba(134, 239, 172, 0.24)",
    },
    trustCellLabel: {
      fontSize: 14,
      fontFamily: fonts.semibold,
      textAlign: "left",
      lineHeight: 19,
      letterSpacing: 0,
      maxWidth: "100%",
      flexShrink: 1,
      marginBottom: homeSpacing.xs,
    },
    trustCellSupport: {
      fontSize: 12,
      fontFamily: fonts.regular,
      lineHeight: 17,
      textAlign: "left",
      maxWidth: "100%",
    },
    trustCellLabelDense: {
      fontSize: typography.overline + 1,
      lineHeight: lineHeight.overline + 2,
      letterSpacing: 0.08,
    },
    productListRow: {
      marginBottom: spacing.md,
      borderRadius: radius.xl + 4,
      overflow: "hidden",
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: isDark ? "rgba(255,255,255,0.08)" : "rgba(63, 63, 70, 0.1)",
      backgroundColor: isDark ? "rgba(255,255,255,0.03)" : "rgba(255, 255, 255, 0.55)",
      ...Platform.select({
        ios: {
          shadowColor: "#18181B",
          shadowOffset: { width: 0, height: 3 },
          shadowOpacity: isDark ? 0.14 : 0.05,
          shadowRadius: 10,
        },
        android: { elevation: isDark ? 2 : 1 },
        web: {
          boxShadow: isDark
            ? "0 8px 24px rgba(0,0,0,0.2), inset 0 1px 0 rgba(255,255,255,0.04)"
            : "0 6px 18px rgba(28, 25, 23, 0.05), inset 0 1px 0 rgba(255,255,255,0.88)",
        },
        default: {},
      }),
    },
    productListRowDivider: {
      marginBottom: spacing.lg,
    },
    productListRowLast: {
      marginBottom: 0,
    },
    heroCardCompact: {
      borderRadius: radius.xxl,
      paddingHorizontal: homeSpacing["2xl"],
      paddingVertical: homeSpacing["2xl"],
      marginBottom: homeSpacing.xl,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: isDark ? c.border : "#E8E6E1",
      backgroundColor: isDark ? c.surface : ALCHEMY.cardBg,
      ...shadowPremium,
    },
    heroTitle: {
      color: c.textPrimary,
      fontSize: typography.h2,
      fontFamily: FONT_DISPLAY,
      letterSpacing: -0.35,
    },
    heroSubtext: {
      marginTop: homeSpacing.sm,
      color: c.textSecondary,
      fontSize: typography.bodySmall,
      fontFamily: fonts.regular,
    },
    categoryQuickNavWrap: {
      marginTop: 0,
      marginBottom: sectionGap,
    },
    toastStackRoot: {
      position: "absolute",
      left: spacing.md,
      right: spacing.md,
      alignItems: "center",
      zIndex: WEB_Z_INDEX.banner,
      elevation: 24,
    },
    toastStackColumn: {
      width: "100%",
      maxWidth: 520,
      alignItems: "stretch",
      gap: 8,
    },
    toastCard: {
      width: "100%",
      borderRadius: 14,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: "rgba(255,255,255,0.2)",
      backgroundColor: ALCHEMY.brownInk,
      ...Platform.select({
        web: {
          boxShadow: "0 12px 24px rgba(15,23,42,0.28)",
        },
        ios: {
          shadowColor: "#000000",
          shadowOffset: { width: 0, height: 8 },
          shadowOpacity: 0.24,
          shadowRadius: 16,
        },
        android: {
          elevation: 10,
        },
        default: {},
      }),
    },
    toastCardInner: {
      flexDirection: "row",
      alignItems: "center",
      gap: homeSpacing.md,
      paddingHorizontal: 16,
      paddingVertical: 12,
    },
    toastText: {
      flex: 1,
      color: "#FFFFFF",
      fontFamily: fonts.regular,
      fontSize: 13,
      lineHeight: Math.round(13 * 1.5),
    },
    toastActionBtn: {
      borderRadius: 8,
      paddingHorizontal: homeSpacing.xs,
      paddingVertical: homeSpacing.xs,
    },
    toastActionBtnPressed: {
      opacity: 0.72,
    },
    toastActionText: {
      color: HERITAGE.amberBright,
      fontFamily: fonts.semibold,
      fontSize: 13,
      lineHeight: Math.round(13 * 1.4),
    },
    liveOrderPinnedWrap: {
      marginBottom: sectionGap,
    },
    activeFilterBar: {
      flexDirection: "row",
      alignItems: "center",
      gap: spacing.sm,
      marginBottom: homeSpacing.lg,
      paddingVertical: homeSpacing.md,
      paddingHorizontal: spacing.lg,
      backgroundColor: c.secondarySoft,
      borderRadius: radius.xl + 2,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.secondaryBorder,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: c.secondaryBorder,
      ...shadowLift,
    },
    activeFilterText: {
      flex: 1,
      color: c.textPrimary,
      fontSize: 13,
      lineHeight: Math.round(13 * 1.5),
      fontFamily: fonts.regular,
    },
    activeFilterClear: {
      color: c.secondaryDark,
      fontSize: 12,
      lineHeight: Math.round(12 * 1.4),
      fontFamily: fonts.semibold,
    },
    sectionFilterBar: {
      flexDirection: "row",
      alignItems: "center",
      gap: spacing.sm,
      marginBottom: homeSpacing.lg,
      paddingVertical: homeSpacing.md,
      paddingHorizontal: spacing.lg,
      backgroundColor: c.secondarySoft,
      borderRadius: radius.xl + 2,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.secondaryBorder,
      borderTopWidth: 2,
      borderTopColor: c.secondary,
      ...shadowLift,
    },
    sectionFilterClear: {
      color: c.secondary,
      fontSize: 12,
      lineHeight: Math.round(12 * 1.4),
      fontFamily: fonts.semibold,
    },
    catalogBrowseBar: {
      flexDirection: "row",
      gap: spacing.sm,
      marginBottom: 0,
      padding: Platform.select({ web: homeSpacing.md, default: homeSpacing.sm }),
      borderRadius: radius.xl + 6,
      borderWidth: StyleSheet.hairlineWidth,
      ...shadowLift,
      ...Platform.select({
        web: {
          width: "100%",
          maxWidth: layout.maxContentWidth,
          alignSelf: "center",
          userSelect: "none",
          boxShadow: isDark
            ? "0 14px 34px rgba(0,0,0,0.28), inset 0 1px 0 rgba(255,255,255,0.04)"
            : "0 12px 28px rgba(24, 24, 27, 0.08), inset 0 1px 0 rgba(255,255,255,0.86)",
        },
        default: {},
      }),
    },
    catalogBrowseBarLight: {
      borderColor: "rgba(63, 63, 70, 0.12)",
      backgroundColor: "rgba(255, 253, 249, 0.94)",
    },
    catalogBrowseBarDark: {
      borderColor: c.border,
      backgroundColor: c.surfaceMuted,
    },
    catalogBrowseOption: {
      flex: 1,
      minWidth: 0,
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: Platform.select({ web: homeSpacing.lg, default: homeSpacing.base }),
      paddingHorizontal: spacing.sm,
      borderRadius: radius.lg + 2,
      gap: homeSpacing.sm,
    },
    catalogBrowseOptionActive: {
      backgroundColor: isDark ? "rgba(148,163,184,0.16)" : "#FFFFFF",
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.secondaryBorder,
      borderTopWidth: 1,
      borderTopColor: c.secondaryBorder,
    },
    catalogBrowseOptionHover: {
      backgroundColor: isDark ? "rgba(148,163,184,0.1)" : "rgba(255,255,255,0.75)",
      ...Platform.select({
        web: {
          boxShadow: isDark
            ? "0 8px 18px rgba(0,0,0,0.2), inset 0 1px 0 rgba(255,255,255,0.04)"
            : "0 8px 16px rgba(24, 24, 27, 0.08), inset 0 1px 0 rgba(255,255,255,0.9)",
        },
        default: {},
      }),
    },
    catalogBrowseOptionPressed: {
      opacity: 0.88,
    },
    catalogBrowseTitle: {
      fontFamily: FONT_DISPLAY_SEMI,
      fontSize: 15,
      letterSpacing: 0.06,
      textAlign: "center",
    },
    catalogBrowseSub: {
      fontSize: 12,
      fontFamily: fonts.medium,
      textAlign: "center",
    },
    sectionChipsScroll: {
      marginBottom: spacing.xl,
      flexGrow: 0,
    },
    sectionChipsContent: {
      flexDirection: "row",
      alignItems: "center",
      gap: spacing.sm,
      paddingBottom: spacing.xs,
      paddingRight: spacing.lg,
    },
    sectionChip: {
      flexDirection: "row",
      alignItems: "center",
      gap: homeSpacing.sm,
      paddingHorizontal: 16,
      paddingVertical: homeSpacing.sm,
      borderRadius: radius.pill,
      borderWidth: StyleSheet.hairlineWidth,
      ...Platform.select({
        web: { cursor: "pointer" },
        default: {},
      }),
    },
    sectionChipActive: {
      borderColor: c.secondaryBorder,
      backgroundColor: c.secondarySoft,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: c.secondaryBorder,
    },
    sectionChipLabel: {
      fontFamily: fonts.bold,
      fontSize: 13,
      maxWidth: 168,
    },
    sectionChipCount: {
      fontSize: 11,
      fontFamily: fonts.semibold,
    },
    catalogIntroCard: {
      marginBottom: homeSpacing.lg,
      borderRadius: 14,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
      backgroundColor: c.surface,
      paddingHorizontal: cardPadding,
      paddingVertical: cardPadding,
      ...Platform.select({
        web: {
          width: "100%",
          maxWidth: layout.maxContentWidth,
          alignSelf: "center",
        },
        default: {},
      }),
    },
    catalogIntroBanner: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: spacing.sm,
      minHeight: 52,
    },
    catalogIntroLeft: {
      flex: 1,
      minWidth: 0,
      gap: homeSpacing.xs,
    },
    catalogIntroEyebrow: {
      fontFamily: fonts.semibold,
      fontSize: 11,
      letterSpacing: 1.4,
      textTransform: "uppercase",
      color: isDark ? c.textMuted : ALCHEMY.brownMuted,
    },
    catalogIntroTitle: {
      color: c.textPrimary,
      fontFamily: FONT_DISPLAY,
      fontSize: windowWidth >= 1024 ? 40 : windowWidth >= 768 ? 32 : 28,
      lineHeight: Math.round((windowWidth >= 1024 ? 40 : windowWidth >= 768 ? 32 : 28) * 1.1),
      letterSpacing: -0.7,
      fontWeight: "500",
    },
    catalogIntroSubtitle: {
      color: c.textSecondary,
      fontFamily: fonts.medium,
      fontSize: typography.bodySmall,
      lineHeight: lineHeight.bodySmall + 3,
      maxWidth: 720,
    },
    catalogViewToggleWrap: {
      position: "relative",
      flexDirection: "row",
      alignItems: "center",
      gap: homeSpacing.sm,
      flexShrink: 0,
    },
    catalogViewToggleBtnTouch: {
      borderRadius: 12,
      ...Platform.select({
        web: { cursor: "pointer" },
        default: {},
      }),
    },
    catalogViewToggleBtn: {
      width: 36,
      height: 36,
      borderRadius: 12,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: c.surface,
      overflow: "hidden",
    },
    catalogViewToggleIconLayer: {
      position: "absolute",
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      alignItems: "center",
      justifyContent: "center",
    },
    catalogViewToggleBtnPressed: {
      opacity: 0.82,
      transform: [{ scale: 0.96 }],
    },
    catalogViewToggleTooltip: {
      position: "absolute",
      top: -28,
      right: 0,
      borderRadius: radius.md,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: isDark ? "rgba(255,255,255,0.16)" : "rgba(100,116,139,0.2)",
      backgroundColor: isDark ? "rgba(24,24,27,0.98)" : "#FFFFFF",
      paddingHorizontal: 8,
      paddingVertical: 4,
      ...Platform.select({
        web: { boxShadow: "0 4px 12px rgba(15,23,42,0.08)" },
        default: {},
      }),
    },
    catalogViewToggleTooltipText: {
      fontSize: typography.caption,
      fontFamily: fonts.medium,
      color: c.textPrimary,
    },
    catalogSkeletonGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: spacing.sm,
    },
    catalogSkeletonCard: {
      width: Platform.OS === "web" ? "calc(33.333% - 10px)" : "48%",
      borderRadius: radius.lg,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: isDark ? "rgba(255,255,255,0.1)" : "rgba(100,116,139,0.18)",
      backgroundColor: c.surface,
      padding: homeSpacing.md,
    },
    catalogSkeletonMeta: {
      paddingTop: homeSpacing.md,
      gap: spacing.xs,
    },
    mobilePeekScroll: {
      marginHorizontal: -2,
    },
    mobilePeekRow: {
      paddingRight: spacing.md,
      gap: spacing.sm,
    },
    mobilePeekItem: {
      minWidth: 148,
      maxWidth: 236,
    },
    inlineSectionEmpty: {
      borderRadius: radius.lg,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: isDark ? "rgba(255,255,255,0.14)" : "rgba(100,116,139,0.2)",
      backgroundColor: isDark ? "rgba(255,255,255,0.03)" : "rgba(248,250,252,0.72)",
      paddingHorizontal: spacing.md,
      paddingVertical: homeSpacing.md,
      gap: homeSpacing.md,
    },
    inlineSectionEmptyTitle: {
      fontSize: 14,
      lineHeight: Math.round(14 * 1.5),
      fontFamily: fonts.regular,
      color: c.textSecondary,
    },
    inlineSectionCategoryRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: spacing.xs,
    },
    inlineSectionCategoryChip: {
      minHeight: 30,
      borderRadius: radius.pill,
      paddingHorizontal: spacing.sm,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: isDark ? "rgba(248,113,113,0.35)" : "rgba(220,38,38,0.22)",
      backgroundColor: isDark ? "rgba(220,38,38,0.1)" : "rgba(220,38,38,0.06)",
      ...Platform.select({
        web: { cursor: "pointer" },
        default: {},
      }),
    },
    inlineSectionCategoryChipPressed: {
      opacity: 0.82,
    },
    inlineSectionCategoryChipText: {
      fontSize: typography.caption,
      fontFamily: fonts.semibold,
      color: c.textPrimary,
    },
    listSection: {
      marginBottom: sectionGap,
    },
    catalogSurface: {
      overflow: "hidden",
      backgroundColor: isDark ? c.surface : ALCHEMY.cardBg,
      borderRadius: radius.xxl,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: isDark ? c.border : "#E8E6E1",
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: isDark ? c.border : "#E8E6E1",
      paddingHorizontal: windowWidth >= 600 ? 20 : 16,
      paddingTop: windowWidth >= 600 ? 20 : 16,
      paddingBottom: windowWidth >= 600 ? 20 : 16,
      ...Platform.select({
        web: {
          width: "100%",
          maxWidth: layout.maxContentWidth,
          alignSelf: "center",
        },
        default: {},
      }),
      ...Platform.select({
        ios: {
          shadowColor: "#18181B",
          shadowOffset: { width: 0, height: 8 },
          shadowOpacity: isDark ? 0.2 : 0.08,
          shadowRadius: 18,
        },
        android: { elevation: isDark ? 4 : 3 },
        web: {
          boxShadow: isDark
            ? "0 16px 42px rgba(0,0,0,0.3), inset 0 1px 0 rgba(255,255,255,0.06)"
            : "0 12px 32px rgba(15, 23, 42, 0.07), 0 4px 12px rgba(24, 24, 27, 0.04), inset 0 1px 0 rgba(255,255,255,0.94)",
        },
        default: {},
      }),
    },
    sectionHeaderRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: spacing.md,
      marginBottom: spacing.md,
      paddingTop: 0,
      paddingBottom: Platform.select({ web: homeSpacing.lg, default: homeSpacing.lg }),
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: isDark ? "rgba(255,255,255,0.1)" : "rgba(63, 63, 70, 0.08)",
    },
    sectionHeaderBlock: {
      flex: 1,
      minWidth: 0,
    },
    sectionTitleRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: spacing.sm,
      flex: 1,
      minWidth: 0,
    },
    sectionHeadingFlex: {
      flex: 1,
      minWidth: 0,
    },
    sectionHeading: {
      fontSize: Platform.OS === "web" ? typography.h2 : typography.h2,
      lineHeight: Platform.OS === "web" ? 30 : 31,
      fontFamily: FONT_DISPLAY,
      color: c.textPrimary,
      letterSpacing: Platform.OS === "web" ? -0.45 : -0.32,
    },
    sectionCountInline: {
      fontSize: typography.caption,
      fontFamily: fonts.semibold,
      paddingHorizontal: homeSpacing.md,
      paddingVertical: 4,
      borderRadius: radius.pill,
      overflow: "hidden",
      backgroundColor: isDark ? "rgba(148,163,184,0.18)" : c.secondarySoft,
      color: c.secondaryDark,
    },
    sectionSeeAllBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: homeSpacing.sm,
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderRadius: radius.pill,
      borderWidth: StyleSheet.hairlineWidth,
      ...Platform.select({
        ios: {
          shadowColor: "#18181B",
          shadowOffset: { width: 0, height: 2 },
          shadowOpacity: 0.06,
          shadowRadius: 6,
        },
        android: { elevation: 2 },
        web: {
          boxShadow: "0 6px 16px rgba(24, 24, 27, 0.09)",
          transition: "background-color 0.18s ease, border-color 0.18s ease, box-shadow 0.18s ease, transform 0.18s ease",
        },
        default: {},
      }),
    },
    sectionSeeAllBtnHover: {
      backgroundColor: isDark ? "rgba(148,163,184,0.16)" : "rgba(255,255,255,0.95)",
      ...Platform.select({
        web: {
          boxShadow: "0 10px 22px rgba(24, 24, 27, 0.12)",
          transform: [{ translateY: -1 }],
        },
        default: {},
      }),
    },
    sectionSeeAll: {
      fontSize: typography.caption,
      fontFamily: fonts.semibold,
      letterSpacing: 0.2,
    },
    emptyLoader: {
      marginBottom: spacing.md,
    },
    productGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: homeSpacing.md,
      alignItems: "flex-start",
      alignContent: "flex-start",
      justifyContent: "flex-start",
    },
    footerFadeBridge: {
      width: "100%",
      maxWidth: layout.maxContentWidth,
      alignSelf: "center",
      height: 64,
      marginTop: -spacing.sm,
    },
    footerWrapper: {
      marginTop: spacing.lg,
      marginBottom: homeSpacing["3xl"],
    },
    pullRefreshOverlay: {
      position: "absolute",
      top: Math.max(safeTopInset, spacing.md) - 10,
      alignSelf: "center",
      width: 28,
      height: 28,
      borderRadius: 999,
      alignItems: "center",
      justifyContent: "center",
      zIndex: WEB_Z_INDEX.sticky + 5,
      backgroundColor: isDark ? "rgba(10,10,10,0.55)" : "rgba(255,255,255,0.85)",
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: homeLine,
    },
    stickyBagBar: {
      position: "absolute",
      left: spacing.md,
      right: spacing.md,
      bottom: CUSTOMER_BOTTOM_NAV_BAR_HEIGHT + Math.max(safeBottomInset, 10) + 16,
      borderRadius: 12,
      backgroundColor: c.navy || c.bgDeep || c.ink || "#0E1729",
      borderTopWidth: 1,
      borderTopColor: "rgba(200,169,126,0.4)",
      paddingVertical: 8,
      paddingHorizontal: 16,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      zIndex: WEB_Z_INDEX.sticky + 8,
    },
    stickyBagText: {
      color: "#FFFFFF",
      fontSize: 11,
      lineHeight: 14,
      fontFamily: fonts.medium,
      letterSpacing: 0.8,
      textTransform: "uppercase",
    },
    stickyBagAmount: {
      color: "#FFFFFF",
      fontSize: 16,
      lineHeight: 18,
      fontFamily: fonts.semibold,
    },
    stickyBagCta: {
      flexDirection: "row",
      alignItems: "center",
      gap: homeSpacing.xs,
      paddingVertical: homeSpacing.xs,
      paddingHorizontal: homeSpacing.base,
      borderRadius: 999,
      backgroundColor: c.accent || "#C8A97E",
    },
    stickyBagCtaPressed: {
      opacity: 0.84,
    },
    stickyBagCtaText: {
      color: c.bgDeep || "#0E1729",
      fontSize: 13,
      lineHeight: Math.round(13 * 1.4),
      fontFamily: fonts.semibold,
    },
    flyGhost: {
      position: "absolute",
      top: 0,
      left: 0,
      width: 48,
      height: 60,
      borderRadius: 8,
      overflow: "hidden",
      zIndex: WEB_Z_INDEX.sticky + 12,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: "rgba(255,255,255,0.55)",
    },
    flyGhostImage: {
      width: "100%",
      height: "100%",
    },
    productGridWrap: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "flex-start",
      columnGap: productGridGap,
      rowGap: productGridGap,
      alignItems: "stretch",
    },
    productGridWrapCentered: {
      justifyContent: "center",
    },
    productGridCell: {
      marginBottom: 0,
      alignSelf: "stretch",
    },
    productGridListContent: {
      paddingBottom: homeSpacing.sm,
    },
    gridCell: {
      marginBottom: 0,
    },
    emptyWrap: {
      paddingVertical: homeSpacing["3xl"],
      alignItems: "center",
      paddingHorizontal: spacing.lg,
      ...Platform.select({
        web: {
          maxWidth: layout.maxContentWidth,
          alignSelf: "center",
          width: "100%",
        },
        default: {},
      }),
    },
    networkErrorWrap: {
      minHeight: 280,
      justifyContent: "center",
      gap: homeSpacing.sm,
    },
    networkErrorIcon: {
      marginBottom: homeSpacing.xs,
    },
    networkErrorTitle: {
      fontFamily: FONT_DISPLAY_SEMI,
      fontSize: 20,
      lineHeight: 24,
      textAlign: "center",
    },
    networkErrorBody: {
      fontFamily: fonts.regular,
      fontSize: 14,
      lineHeight: Math.round(14 * 1.45),
      textAlign: "center",
      maxWidth: 360,
    },
    networkRetryBtn: {
      marginTop: homeSpacing.sm,
      borderRadius: radius.pill,
      minHeight: 44,
      paddingHorizontal: homeSpacing.lg,
      alignItems: "center",
      justifyContent: "center",
    },
    networkRetryBtnPressed: {
      opacity: 0.9,
      transform: [{ scale: 0.98 }],
    },
    networkRetryBtnText: {
      color: "#FFFFFF",
      fontFamily: fonts.semibold,
      fontSize: 14,
      lineHeight: Math.round(14 * 1.4),
    },
    searchEmptyWrap: {
      gap: homeSpacing.sm,
      marginBottom: sectionGap,
    },
    searchEmptyTitle: {
      fontFamily: FONT_DISPLAY_SEMI,
      fontSize: 20,
      lineHeight: 24,
      textAlign: "center",
    },
    searchEmptyBody: {
      fontFamily: fonts.regular,
      fontSize: 14,
      lineHeight: Math.round(14 * 1.45),
      textAlign: "center",
      maxWidth: 380,
    },
    searchEmptyClearBtn: {
      marginTop: homeSpacing.sm,
      borderRadius: radius.pill,
      borderWidth: StyleSheet.hairlineWidth,
      minHeight: 42,
      paddingHorizontal: homeSpacing.lg,
      alignItems: "center",
      justifyContent: "center",
    },
    searchEmptyClearBtnPressed: {
      opacity: 0.85,
    },
    searchEmptyClearBtnText: {
      fontFamily: fonts.semibold,
      fontSize: 13,
      lineHeight: Math.round(13 * 1.4),
      letterSpacing: 0.2,
    },
    emptyIconCircle: {
      width: 96,
      height: 96,
      borderRadius: radius.xxl,
      backgroundColor: c.secondarySoft,
      borderWidth: 1.5,
      borderColor: c.secondaryBorder,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: spacing.lg,
      ...shadowLift,
    },
    emptyText: {
      textAlign: "center",
      color: c.textSecondary,
      fontSize: typography.bodySmall + 1,
      lineHeight: lineHeight.bodySmall + 4,
      fontFamily: fonts.medium,
      maxWidth: 340,
    },
    errorText: {
      flex: 1,
      fontSize: 14,
      lineHeight: Math.round(14 * 1.5),
      fontFamily: fonts.semibold,
    },
    emptySectionHint: {
      alignItems: "center",
      gap: spacing.sm,
      marginBottom: homeSpacing.lg,
      paddingVertical: spacing.md,
    },
    emptySectionText: {
      fontSize: typography.bodySmall,
      fontFamily: fonts.medium,
      color: c.textSecondary,
      textAlign: "center",
    },
    emptySectionClear: {
      fontSize: typography.bodySmall,
      fontFamily: fonts.semibold,
      color: c.secondary,
    },
    menuModalRoot: {
      flex: 1,
      backgroundColor: "transparent",
    },
    menuBackdrop: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: "rgba(12, 10, 8, 0.5)",
      zIndex: 0,
    },
    menuLayer: {
      ...StyleSheet.absoluteFillObject,
      zIndex: 1,
    },
    menuDropdown: {
      position: "absolute",
      minWidth: 288,
      maxWidth: "92%",
      borderRadius: radius.xxl + 2,
      borderWidth: StyleSheet.hairlineWidth,
      paddingBottom: spacing.lg,
      overflow: "hidden",
      ...Platform.select({
        ios: {
          shadowColor: "#000",
          shadowOffset: { width: 0, height: 14 },
          shadowOpacity: 0.28,
          shadowRadius: 24,
        },
        android: { elevation: 14 },
        web: {
          boxShadow: "0 20px 50px rgba(12, 10, 8, 0.28)",
          zIndex: WEB_Z_INDEX.dropdown,
        },
        default: {},
      }),
    },
    menuGoldAccent: {
      height: 3,
      width: "100%",
      opacity: 0.95,
    },
    menuHeaderRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: homeSpacing.lg,
      paddingTop: homeSpacing.md,
      paddingBottom: homeSpacing.md,
    },
    menuHeaderTitle: {
      fontFamily: FONT_DISPLAY,
      fontSize: typography.h2,
      lineHeight: Math.round(typography.h2 * 1.1),
      letterSpacing: -(typography.h2 * 0.025),
      fontWeight: "500",
    },
    menuCloseBtn: {
      padding: homeSpacing.xs,
      borderRadius: radius.sm,
    },
    menuSectionLabel: {
      fontSize: 11,
      fontFamily: fonts.semibold,
      letterSpacing: 1.4,
      textTransform: "uppercase",
      paddingHorizontal: spacing.md,
      paddingTop: spacing.xs,
      paddingBottom: homeSpacing.sm,
    },
    menuRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: spacing.sm,
      marginHorizontal: spacing.sm,
      marginBottom: homeSpacing.xs,
      paddingVertical: 12,
      paddingHorizontal: spacing.sm,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: isDark ? "rgba(255,255,255,0.06)" : "rgba(63, 63, 70, 0.08)",
    },
    menuRowHover: {
      backgroundColor: isDark ? "rgba(148,163,184,0.08)" : "rgba(100, 116, 139, 0.08)",
    },
    menuRowSelected: {
      borderWidth: 1,
    },
    menuRowPressed: {
      opacity: 0.88,
    },
    menuIconCircle: {
      width: 40,
      height: 40,
      borderRadius: 12,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: isDark ? "rgba(255,255,255,0.1)" : "rgba(63, 63, 70, 0.16)",
    },
    menuRowTextCol: {
      flex: 1,
      minWidth: 0,
    },
    menuRowTitle: {
      fontSize: 14,
      lineHeight: Math.round(14 * 1.5),
      fontFamily: fonts.medium,
      letterSpacing: 0.1,
    },
    menuRowValue: {
      marginTop: homeSpacing.xs,
      fontSize: typography.caption,
      fontFamily: fonts.regular,
      lineHeight: Math.round(12 * 1.4),
    },
    menuPillActive: {
      paddingHorizontal: 8,
      paddingVertical: homeSpacing.xs,
      borderRadius: radius.pill,
      borderWidth: 1,
    },
    menuPillActiveText: {
      fontSize: 10,
      fontFamily: fonts.semibold,
      letterSpacing: 0.4,
      textTransform: "uppercase",
    },
    menuCheckPlaceholder: {
      width: 56,
      height: 24,
    },
    peNone: {
      pointerEvents: "none",
    },
    peBoxNone: {
      pointerEvents: "box-none",
    },
    notifyModalRoot: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: homeSpacing.lg,
      paddingVertical: homeSpacing["2xl"],
    },
    notifyModalBackdrop: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: "rgba(0,0,0,0.4)",
    },
    notifyModalCard: {
      width: "100%",
      maxWidth: 420,
      borderRadius: radius.xl,
      borderWidth: StyleSheet.hairlineWidth,
      paddingHorizontal: homeSpacing.lg,
      paddingVertical: homeSpacing.lg,
      gap: homeSpacing.sm,
    },
    notifyModalTitle: {
      fontFamily: FONT_DISPLAY_SEMI,
      fontSize: 22,
      lineHeight: 26,
    },
    notifyModalBody: {
      fontFamily: fonts.regular,
      fontSize: 14,
      lineHeight: Math.round(14 * 1.45),
    },
    notifyModalInput: {
      minHeight: 44,
      borderRadius: radius.md,
      borderWidth: StyleSheet.hairlineWidth,
      paddingHorizontal: homeSpacing.md,
      fontFamily: fonts.regular,
      fontSize: 14,
    },
    notifyModalSuccess: {
      fontFamily: fonts.medium,
      fontSize: 14,
      lineHeight: Math.round(14 * 1.4),
    },
    notifyModalActions: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "flex-end",
      gap: homeSpacing.sm,
      marginTop: homeSpacing.xs,
    },
    notifyModalPrimaryBtn: {
      borderRadius: radius.pill,
      minHeight: 40,
      paddingHorizontal: homeSpacing.base,
      alignItems: "center",
      justifyContent: "center",
    },
    notifyModalPrimaryText: {
      color: "#FFFFFF",
      fontFamily: fonts.semibold,
      fontSize: 13,
      lineHeight: Math.round(13 * 1.4),
    },
    notifyModalGhostBtn: {
      borderRadius: radius.pill,
      borderWidth: StyleSheet.hairlineWidth,
      minHeight: 40,
      paddingHorizontal: homeSpacing.base,
      alignItems: "center",
      justifyContent: "center",
    },
    notifyModalGhostText: {
      fontFamily: fonts.semibold,
      fontSize: 13,
      lineHeight: Math.round(13 * 1.4),
    },
    notifyModalBtnPressed: {
      opacity: 0.85,
    },
  });
}

export { createHomeStyles, HOME_HEADER_INK, HOME_LINE };
