import AccountNavigator from "./AccountNavigator";
import BlogIndexScreen from "../screens/editorial/BlogIndexScreen";
import BlogPostScreen from "../screens/editorial/BlogPostScreen";
import CartScreen from "../screens/CartScreen";
import CategoriesScreen from "../screens/CategoriesScreen";
import ContactScreen from "../screens/editorial/ContactScreen";
import DevDebugScreen from "../screens/DevDebugScreen";
import FaqScreen from "../screens/editorial/FaqScreen";
import ForgotPasswordScreen from "../screens/ForgotPasswordScreen";
import LoginScreen from "../screens/LoginScreen";
import NotFoundScreen from "../screens/NotFoundScreen";
import NotificationsScreen from "../screens/NotificationsScreen";
import PolicyScreen from "../screens/editorial/PolicyScreen";
import ProductScreen from "../screens/ProductScreen";
import RedeemRewardsScreen from "../screens/RedeemRewardsScreen";
import RegisterScreen from "../screens/RegisterScreen";
import ResetPasswordScreen from "../screens/ResetPasswordScreen";
import ReviewsScreen from "../screens/ReviewsScreen";
import SearchScreen from "../screens/SearchScreen";
import SupportScreen from "../screens/SupportScreen";
import TrustInfoScreen from "../screens/TrustInfoScreen";
import VerifyEmailScreen from "../screens/VerifyEmailScreen";
import AboutScreen from "../screens/editorial/AboutScreen";

/** Native keeps eager imports; web file splits these routes. */
export const LazyAboutScreen = AboutScreen;
export const LazyAccountNavigator = AccountNavigator;
export const LazyBlogIndexScreen = BlogIndexScreen;
export const LazyBlogPostScreen = BlogPostScreen;
export const LazyCartScreen = CartScreen;
export const LazyCategoriesScreen = CategoriesScreen;
export const LazyContactScreen = ContactScreen;
export const LazyDevDebugScreen = DevDebugScreen;
export const LazyFaqScreen = FaqScreen;
export const LazyForgotPasswordScreen = ForgotPasswordScreen;
export const LazyLoginScreen = LoginScreen;
export const LazyNotFoundScreen = NotFoundScreen;
export const LazyNotificationsScreen = NotificationsScreen;
export const LazyPolicyScreen = PolicyScreen;
export const LazyProductScreen = ProductScreen;
export const LazyRedeemRewardsScreen = RedeemRewardsScreen;
export const LazyRegisterScreen = RegisterScreen;
export const LazyResetPasswordScreen = ResetPasswordScreen;
export const LazyReviewsScreen = ReviewsScreen;
export const LazySearchScreen = SearchScreen;
export const LazySupportScreen = SupportScreen;
export const LazyTrustInfoScreen = TrustInfoScreen;
export const LazyVerifyEmailScreen = VerifyEmailScreen;
