/**
 * Web hero assets — WebP delivery variants (generated by `npm run optimize:web`).
 */
export {
  WEB_HERO_WIDE_RATIO,
  WEB_HERO_TEL_WIDE_RATIO,
  WEB_HERO_MASALA_WIDE_RATIO,
  WEB_HERO_TEL_PORTRAIT_RATIO,
  WEB_HERO_MASALA_PORTRAIT_RATIO,
  WEB_HERO_HONEY_WIDE_RATIO,
  WEB_HERO_HONEY_PORTRAIT_RATIO,
  WEB_HERO_PRODUCT_RATIO,
  WEB_HERO_PORTRAIT_RATIO,
  HOME_HERO_PACKAGING,
  HOME_WEB_INTRO,
} from "./homeHeroContent.shared";

export const HOME_HERO_ASSETS = {
  get webWide() {
    return require("../../assets/zeevan-hero-web-21x9-web-960.webp");
  },
  get webTelWide() {
    return require("../../assets/zeevan-hero-web-tel-21x9-web-960.webp");
  },
  get webMasalaWide() {
    return require("../../assets/zeevan-hero-web-masala-21x9-web-960.webp");
  },
  get telMobile() {
    return require("../../assets/zeevan-tel-portrait-web-720.webp");
  },
  get masalaMobile() {
    return require("../../assets/zeevan-masala-portrait-web-720.webp");
  },
  get webHoneyWide() {
    return require("../../assets/zeevan-hero-web-honey-21x9-web-960.webp");
  },
  get honeyMobile() {
    return require("../../assets/zeevan-honey-portrait-web-720.webp");
  },
  get packagingMobile() {
    return require("../../assets/zeevan-ghee-packaging-portrait-web-720.webp");
  },
};
